apiVersion: apps/v1
kind: Deployment
metadata:
  name: green-deployment
  labels:
    app: green-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: green-app
  template:
    metadata:
      labels:
        app: green-app
    spec:
      containers:
      - name: green-app
        image: 053273560072.dkr.ecr.ap-southeast-2.amazonaws.com/green-app
        ports:
        - containerPort: 80

