apiVersion: v1
kind: Service
metadata:
  name: blue-service
  annotations:
  labels:
    app: live
spec:
  selector:
    app: blue-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
  externalTrafficPolicy: Cluster
